### ISSUE TITLE
Issue with Substitution

### ISSUE THREAD

**Issue by margauxw** [florale/multilevelcoda#6]
Hello,

I keep getting the following error

Error in `[.data.frame`(d0, , colnames(d0) %in% colnames(object$CompILR$data),  : 
  unused argument (with = FALSE)

Code:
subm2 <- substitution(object = model1, delta = 1:2 ref = "clustermean", level ="within", weight = 'proportional')

I get it to work with 'grandmean', but only if I add weight = 'proportional' (which I was planning to do anyway) - but this does not fix it for clustermean. Changing the delta, level, or weight doesn't fix it. 

Removing weights gives (for both grandmean/clustermean setting)
Error in `[.data.frame`(d0, , head(.SD, 1), by = eval(object$CompILR$idvar)) : 
  unused argument (by = eval(object$CompILR$idvar))

Model 1's output looks fine and output of the substitution model for the grandmean as well.

**Comment by florale** [comment]
I can't quite diagnose given your code. Could you provide a reproducible example?

**Comment by trishakohhub** [comment]
I have the same issue!

Dear Dr Le,

Thank you for developing and maintaining multilevelcoda — it has been central to my analysis of a compositional daily-activity dataset (sleep, sedentary behaviour, light PA, and MVPA, totalling 1440 minutes/day) with repeated measures nested within subjects.

I have run into what appears to be a reproducible bug in substitution() when combining a within-person level with a clustermean reference and the one-to-all substitution type. The call is:

substitution(mlm_all_alert, delta = 30, ref = "clustermean",
             level = "within", type = "one-to-all", weight = "proportional",
             allow_new_levels = TRUE)

which fails with:
Warning: Caught simpleError. Canceling all iterations ...
Error in `[.data.table`(d1, , `:=`(To, sub_to_var)) :
  Supplied 2 items to be assigned to 463 items of column 'To'. If you wish to
  'recycle' the RHS please use rep() to make this intent clear to readers of your code.

The number on the right-hand side (463 here) tracks my subject count exactly — when I removed three single-observation subjects it changed from 466 to 463 — so the clustermean reference grid appears to be correctly sized to one row per subject, but the internal To label vector has length 2 and cannot be recycled to that length during the := assignment.

Some observations that may help localise it:

The same model works fine for other configurations. Specifically, 
(1) substitution(mlm_all_alert, delta = 30, ref = "grandmean",
             level = "between", type = "one-to-all", weight = "proportional",
             allow_new_levels = TRUE)

(2) substitution(mlm_all_alert, delta = 30, ref = "clustermean",
             level = "within", type = "one-to-one", weight = "proportional",
             allow_new_levels = TRUE)

(3) substitution(mlm_all_alert, delta = 30,
             level = c("between", "within"), type = "one-to-one", weight = "proportional")
call without an explicit ref also works, but it defaults the within level to grandmean rather than clustermean (confirmed via the Reference column in the output)

Only the specific combination of within + clustermean + one-to-all fails.

I have ruled out data-side causes: there are no single-observation subjects after filtering, no subjects with zero within-person variance in the composition and coercing the categorical covariates (sex, weekend, role) to factors before fitting did not resolve it. The error persists on both the CRAN version (1.3.3) and the current GitHub HEAD. I look forward to your response and assistance with regards to this issue, thank you!
